apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
      - name: binarycalculator
        image: northamerica-northeast2-docker.pkg.dev/alien-span-452023-p7/sofe3980u/binarycalculator:latest
        ports:
        - containerPort: 8080
